version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        container_name: travellist-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./:/var/www
        networks:
            - travellist
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"

    db:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: example
            MYSQL_ROOT_PASSWORD: Tuscano32
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my_dev.cnf:/etc/my.cnf.d/my.cnf
        networks:
            - travellist

    nginx:
        image: nginx:alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - travellist

    node:
        container_name: node
        image: "node:14"
        user: "node"
        working_dir: /var/www/
        tty: true
        volumes:
            - ./:/var/www

networks:
    travellist:
        driver: bridge
