FROM python:3.8

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

COPY ./python/requirements.txt requirements.txt

RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt
COPY ./python/app.py .

EXPOSE 5000
WORKDIR /var/www/
CMD ["flask", "run"]
