version: "3.7"
services:
    php-base:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./php/base
        image: php-base
        container_name: php-base
        restart: unless-stopped
        volumes:
            - ../docker/php:/usr/local/etc/php/conf.d/
            - ../:/var/www
        networks:
            - laravel
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"

    mysql:
        image: mysql:8.0
        container_name: mysql
#        platform: linux/x86_64
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: portal
            MYSQL_ROOT_PASSWORD: BasePortal
            DB_USER: root
            DB_PASSWORD: BasePortal
            SERVICE_NAME: mysql
#        volumes:
#            - ../structure/mysql/data:/var/lib/mysql
#            - ../structure/mysql/my_dev.cnf:/etc/my.cnf.d/my.cnf
        networks:
            - laravel
        depends_on:
            - php-base

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        depends_on:
            - php-base
        environment:
            - NGINX_PORT=8080
        ports:
            - "8080:80"
        volumes:
            - ../:/var/www
            - ./nginx/config/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    #    python:
    #        container_name: python
    #        working_dir: /var/www/
    #        volumes:
    #            - .:/var/www/
    #        environment:
    #            FLASK_ENV: development
    #        build:
    #            context: .
    #            dockerfile: Dockerfile-python
    #        ports:
    #            - "5000:5000"
#    rabbitmq:
#        image: "rabbitmq:3-management"
#        restart: unless-stopped
#        hostname: "rabbit"
#        ports:
#            - "15672:15672"
#            - "5672:5672"
#        volumes:
#            - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config

    node:
        container_name: node
        image: "node:14"
        restart: unless-stopped
        user: "node"
        working_dir: /var/www/nextjs
        tty: true
        ports:
            - "80:3000"
        volumes:
            - ../:/var/www/

#    sockets:
#        build:
#            context: .
#            dockerfile: Dockerfile-sockets
#        container_name: sockets
#        volumes:
#            - ./:/var/www
#        ports:
#            - "6001:6001"
#        networks:
#            - laravel
#        command: npm run production
#    redis:
#        image: redis:alpine
#        container_name: redis
#        working_dir: /var/www/
#        build:
#            context: .
#            dockerfile: Dockerfile-redis
#        volumes:
#            - ./data/redis:/var/www/data
#        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
#        networks:
#            - laravel
#        ports:
#            - "6379:6379"
#
#    queues:
#        build: ./build
#        container_name: queues
#        command: php artisan horizon
#        volumes:
#            - ./code:/application

networks:
    laravel:
