version: "3.7"
services:
    php-base:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./php/base
        image: php-base
        container_name: php-base
        restart: unless-stopped
        volumes:
            - ../docker/php:/usr/local/etc/php/conf.d/
            - ../:/var/www
        networks:
            - laravel
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"

    mysql:
        image: mysql:8.0
        container_name: mysql
#        platform: linux/x86_64
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: portal
            MYSQL_ROOT_PASSWORD: BasePortal
            DB_USER: root
            DB_PASSWORD: BasePortal
            SERVICE_NAME: mysql
        volumes:
            - ../structure/mysql/data:/var/lib/mysql
#            - ../structure/mysql/my_dev.cnf:/etc/my.cnf.d/my.cnf
        networks:
            - laravel
        depends_on:
            - php-base

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        depends_on:
            - php-base
        environment:
            - NGINX_PORT=8080
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ../:/var/www
          - ./nginx/config/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./nginx/cert.pem:/etc/cert.pem
          - ./nginx/key.pem:/etc/key.pem
          - ./nginx/logs:/var/log/nginx
        networks:
            - laravel

    node:
        container_name: node
        image: "node:14"
        restart: unless-stopped
        user: "node"
        working_dir: /var/www/nextjs
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - ../:/var/www/
#    certbot:
#      ports:
#        - "6000:80"
#      volumes:
#        - ./nginx/:/etc/nginx/
#      build:
#        context: ./certbot
#        dockerfile: Dockerfile
#        args:
#          DOMAIN_EMAIL: ${DOMAIN_EMAIL}
#          DOMAIN_URL: '${DOMAIN_URL}

networks:
    laravel:
