<?php

namespace App\Custom;

use Illuminate\Database\Eloquent\Collection;

class CustomCollection extends Collection
{
    public function first(callable $callback = null, $default = null): static
    {
        return parent::first($callback, $default); // TODO: Change the autogenerated stub
    }
}
